name: "Raphaël Fournier : blog"
description: "Raphael Fournier : blog"
url: http://www.raphaelfournier.net
title:              Raphaël Fournier
author:             Raphaël Fournier

safe:        false
auto:        true
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

exclude: Rakefile

# plugins
category_dir:       categories
code_dir:           code
post_types:
  - portfolio
index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  tag:
    do_related:     true
    title_prefix:   'Tag: '
############################    

future:      true
lsi:         false
markdown: rdiscount
pygments: true
paginate: 6
#permalink: /:year/:month/:day/:title
permalink: pretty
rdiscount:
  extensions: [smart]

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

#project_dir: projects
category_dir: 'tags'
category_title_prefix: 'Posts tagged '
archive_yearly: true
archive_monthly: true
archive_daily: true

# indextank settings
indextank_index: my_index
indextank_api_url: http://:myapikey@myapi.api.indextank.com

# these values are applied as regular expressions
indextank_excludes: [index.html, 404.html, ^/secret/]
